[[redirects]]
  from = "/api/webhook/payment-confirm"
  to = "/.netlify/functions/payment-confirm"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/payment-confirm/*"
  to = "/.netlify/functions/payment-confirm"
  status = 200
  force = true
